version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web_all_the_rest
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - /var/www/all-the.rest:/usr/share/nginx/html:ro
