version: '3'

services:
  website:
    image: nginx:alpine
    container_name: reisinger-pictures
    restart: unless-stopped
    volumes:
      - /home/webadmin/websites/reisinger.pictures:/usr/share/nginx/html:ro
    networks:
      webnet:
        ipv4_address: 172.18.0.10

networks:
  webnet:
    external: true