version: '3'

services:
  website:
    image: nginx:alpine
    container_name: reisinger-pictures
    restart: unless-stopped
    volumes:
      - /home/webadmin/websites/reisinger.pictures:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    external: true